"""Generates an MMPose config .py file for one (dataset, task, seed) cell,
adapted from the official rtmpose-s_8xb256-420e_coco-256x192.py per every
lock in PROTOCOL_LOCKED.md.

NEEDS LIVE-ENVIRONMENT VERIFICATION (see README.md "What still needs a live
environment"): the exact field names/shapes below were cross-checked against
the official config's documented structure (backbone init_cfg/prefix, codec
args, head args, pipeline transform list) but this project has not yet
imported mmpose to confirm the generated config actually builds a model and
runs a forward pass. Run PREFLIGHT_ONLY-style config validation (build the
model, print structure, run one dummy batch) before spending GPU time.

Deliberate deviations from the official recipe, each one because
PROTOCOL_LOCKED.md or the supervisor's email requires it, not because the
official recipe was copied carelessly:
  - out_channels=2 (not 17), in_featuremap_size=(16,16) (not (6,8)),
    input_size=(512,512) (not (192,256)): two-endpoint task, 512x512 lock.
  - sigma=(8.0,8.0): extrapolated per PROTOCOL_LOCKED.md, not an official
    512x512 value -- said explicitly in a config comment, not just the
    surrounding docs, so it cannot be missed by someone reading the .py file
    in isolation.
  - GetBBoxCenterScale + TopdownAffine replaced by PixelCentreResize in both
    train and val pipelines.
  - RandomHalfBody removed entirely (supervisor's explicit instruction --
    a person-specific augmentation with no meaning for a two-endpoint
    fetal measurement).
  - test_cfg flip_test=False: this project already investigated and
    abandoned flip-based TTA for two-endpoint fetal tasks (thesis
    sec:method-tta) because endpoint-order canonicalisation is unstable
    under flip for near-vertical diameters; enabling RTMPose's own
    flip-test would silently reintroduce the exact failure mode already
    documented and avoided for EoMT.
  - Rotation/scale/flip augmentation (RandomBBoxTransform/RandomFlip) is
    NOT delegated to MMPose's stock transforms; a custom FetalTrainAugment
    (transforms.py) replaces all three. CORRECTED 2026-08-06 after
    audit_flip_order_stability.py measured that a static flip_indices
    setting (this file's earlier version) is silently wrong for 100% of
    UCL OFD/APAD/FL training images (see fetal_augment.py's module
    docstring and PROTOCOL_AUDIT.md) -- FetalTrainAugment re-derives the
    DOD-canonical order after every accepted flip/rotation, matching the
    audited upstream HRNet's own per-sample re-projection architecture,
    and also adds the rotation (ROT_FACTOR=30, p=0.6) + scale
    (SCALE_FACTOR=0.25, unconditional) augmentation this file's previous
    version deferred entirely -- see PROTOCOL_AUDIT.md's augmentation
    item-by-item table for what does/doesn't match EoMT/HRNet exactly.
  - Backbone-only pretrained init via prefix='backbone.'; RTMCCHead fully
    randomly initialised (matches the OFFICIAL recipe's own convention,
    confirmed against the real config -- not a compromise specific to this
    adaptation).
"""

from __future__ import annotations

from pathlib import Path

OFFICIAL_CSPNEXT_S_BACKBONE_CHECKPOINT = (
    "https://download.openmmlab.com/mmpose/v1/projects/rtmposev1/"
    "cspnext-s_udp-aic-coco_210e-256x192-92f5a029_20230130.pth"
)

TEMPLATE = '''\
# AUTO-GENERATED by rtmpose_reproduction/make_config.py -- do not hand-edit.
# dataset={dataset} task={task} seed={seed}
# See rtmpose_reproduction/PROTOCOL_LOCKED.md and make_config.py's own
# module docstring for what was locked/changed and why.

import sys
sys.path.insert(0, {repo_root!r})  # for transforms.py / fetal_dataset_info.py

default_scope = "mmpose"
randomness = dict(seed={seed}, deterministic=True)

# --- import the custom transform so @TRANSFORMS.register_module() runs ---
import transforms  # noqa: F401,E402
from fetal_dataset_info import FETAL_DATASET_INFO  # noqa: E402
from dod_vectors import get_d_vect  # noqa: E402

# Frozen DOD prototype vector for this (dataset, task), reused verbatim from
# the audited upstream HRNet reproduction (dod_vectors.py) -- FetalTrainAugment
# uses this to re-derive the canonical channel order after every accepted
# flip/rotation, replacing the old static-flip_indices design (see
# fetal_augment.py's module docstring and PROTOCOL_AUDIT.md).
d_vect = get_d_vect({dataset!r}, {task!r})

input_size = (512, 512)

codec = dict(
    type="SimCCLabel",
    input_size=input_size,
    sigma=(8.0, 8.0),  # EXTRAPOLATED value, not an official 512x512 setting
                        # -- see PROTOCOL_LOCKED.md for the sigma_axis =
                        # sqrt(axis_length / 8) derivation from the two real
                        # official (192,256)/(288,384) configs.
    simcc_split_ratio=2.0,
    normalize=False,
    use_dark=False,
)

model = dict(
    type="TopdownPoseEstimator",
    data_preprocessor=dict(
        type="PoseDataPreprocessor",
        mean=[123.675, 116.28, 103.53],
        std=[58.395, 57.12, 57.375],
        bgr_to_rgb=True,
    ),
    backbone=dict(
        type="CSPNeXt",
        arch="P5",
        deepen_factor=0.33,
        widen_factor=0.5,
        out_indices=(4,),
        channel_attention=True,
        norm_cfg=dict(type="BN"),
        act_cfg=dict(type="SiLU", inplace=True),
        init_cfg=dict(
            type="Pretrained",
            prefix="backbone.",
            checkpoint={backbone_checkpoint!r},
        ),
    ),
    head=dict(
        type="RTMCCHead",
        in_channels=512,
        out_channels=2,          # LOCKED: two endpoints, not COCO's 17
        input_size=input_size,   # LOCKED: 512x512, not (192,256)
        in_featuremap_size=(16, 16),  # = input_size / 32 (stride-32 backbone stage)
        simcc_split_ratio=2.0,
        final_layer_kernel_size=7,
        gau_cfg=dict(
            hidden_dims=256, s=128, expansion_factor=2,
            dropout_rate=0.0, drop_path=0.0, act_fn="SiLU",
            use_rel_bias=False, pos_enc=False,
        ),
        loss=dict(
            type="KLDiscretLoss", use_target_weight=True,
            beta=10.0, label_softmax=True,
        ),
        decoder=codec,
    ),
    test_cfg=dict(
        flip_test=False,  # LOCKED off: see module docstring (endpoint-order
                           # instability under flip for near-vertical
                           # diameters, already documented for EoMT's TTA).
    ),
)

# --- data ---
dataset_type = "CocoDataset"
data_mode = "topdown"

train_pipeline = [
    dict(type="LoadImage"),
    # RandomHalfBody deliberately removed (supervisor instruction).
    dict(type="PixelCentreResize", input_size=512),
    # Replaces RandomFlip + RandomBBoxTransform: flip (p=0.5), rotation
    # (+-30 deg, p=0.6), scale (0.75-1.25, unconditional), colour jitter,
    # ALL with DOD-consistent re-canonicalisation after every accepted
    # geometric draw. See transforms.FetalTrainAugment's own docstring and
    # PROTOCOL_AUDIT.md for what this fixes and what remains disclosed as
    # non-bit-identical to EoMT/HRNet.
    dict(type="FetalTrainAugment", d_vect=d_vect, input_size=512),
    dict(type="GenerateTarget", encoder=codec),
    dict(type="PackPoseInputs"),
]

val_pipeline = [
    dict(type="LoadImage"),
    dict(type="PixelCentreResize", input_size=512),
    dict(type="PackPoseInputs"),
]

train_dataloader = dict(
    batch_size={batch_size},
    num_workers=4,
    persistent_workers=True,
    sampler=dict(type="DefaultSampler", shuffle=True, seed={seed}),
    dataset=dict(
        type=dataset_type,
        data_root={data_root!r},
        data_mode=data_mode,
        ann_file={train_ann!r},
        data_prefix=dict(img={images_dir!r}),
        metainfo=FETAL_DATASET_INFO,
        pipeline=train_pipeline,
    ),
)

val_dataloader = dict(
    batch_size={batch_size},
    num_workers=4,
    persistent_workers=True,
    drop_last=False,
    sampler=dict(type="DefaultSampler", shuffle=False),
    dataset=dict(
        type=dataset_type,
        data_root={data_root!r},
        data_mode=data_mode,
        ann_file={test_ann!r},
        data_prefix=dict(img={images_dir!r}),
        metainfo=FETAL_DATASET_INFO,
        pipeline=val_pipeline,
        test_mode=True,
    ),
)
test_dataloader = val_dataloader

# Internal training-time sanity metric ONLY -- NOT the reported number.
# The authoritative fixed-channel/swap-min NME comes from
# evaluate_rtmpose_fixed.py run on run_inference.py's exported, original-
# image-space predictions, using the identical formula as HRNet's evaluator.
val_evaluator = dict(type="PCKAccuracy", thr=0.05)
test_evaluator = val_evaluator

train_cfg = dict(by_epoch=True, max_epochs={max_epochs}, val_interval={val_interval})
val_cfg = dict()
test_cfg = dict()

optim_wrapper = dict(
    type="OptimWrapper",
    optimizer=dict(type="AdamW", lr=4e-3, weight_decay=0.0),
)
param_scheduler = [
    dict(type="LinearLR", start_factor=1e-5, by_epoch=False, begin=0, end=1000),
    dict(type="CosineAnnealingLR", eta_min=0.0002, begin=0, end={max_epochs},
         T_max={max_epochs}, by_epoch=True, convert_to_iter_based=True),
]

default_hooks = dict(
    checkpoint=dict(
        type="CheckpointHook", interval={val_interval}, save_best="PCK",
        rule="greater", max_keep_ckpts=1,
    ),
    logger=dict(type="LoggerHook", interval=10),
)

work_dir = {work_dir!r}
'''


def make_config(dataset: str, task: str, seed: int, data_root: str,
                 images_dir: str, train_ann: str, test_ann: str,
                 work_dir: str, out_path: Path,
                 batch_size: int = 16, max_epochs: int = 200,
                 val_interval: int = 5, repo_root: str | None = None) -> Path:
    text = TEMPLATE.format(
        dataset=dataset, task=task, seed=seed,
        repo_root=repo_root or str(Path(__file__).resolve().parent),
        backbone_checkpoint=OFFICIAL_CSPNEXT_S_BACKBONE_CHECKPOINT,
        data_root=data_root, images_dir=images_dir,
        train_ann=train_ann, test_ann=test_ann,
        batch_size=batch_size, max_epochs=max_epochs, val_interval=val_interval,
        work_dir=work_dir,
    )
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(text, encoding="utf-8")
    return out_path


if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument("--dataset", required=True, choices=["UCL", "MULTICENTRE"])
    parser.add_argument("--task", required=True, choices=["BPD", "OFD", "APAD", "TAD", "FL"])
    parser.add_argument("--seed", required=True, type=int)
    parser.add_argument("--data-root", required=True)
    parser.add_argument("--images-dir", required=True)
    parser.add_argument("--train-ann", required=True)
    parser.add_argument("--test-ann", required=True)
    parser.add_argument("--work-dir", required=True)
    parser.add_argument("--out", required=True, type=Path)
    args = parser.parse_args()
    path = make_config(args.dataset, args.task, args.seed, args.data_root,
                        args.images_dir, args.train_ann, args.test_ann,
                        args.work_dir, args.out)
    print(f"[OK] wrote {path}")
